esphome:
  name: babybuddy-panel
#USB Powered version.
#Supports single, double, triple, hold.
esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Babybuddy-Panel Fallback Hotspot"
    password: !secret hotspot_password

captive_portal:

#connections: all buttons are on VIN and on their respective pins
#(we are relying on esp32s built-in pulldown resistors but could have used external resistors as well)
#sleepstart: GPIO26
#sleepstop: GPIO33
#tummytimestart: GPIO25 
#tummytimestop: GPIO32
#feedingstart: GPIO27
#feedingstop: GPIO14
#diaperwet: GPIO12
#diapersolid: GPIO13

binary_sensor:
  # key sleep stop
  - platform: gpio
    pin:
      number: GPIO33
      mode:
        input: true
        pulldown: true #was pulldown
    id: sleepstop
    on_multi_click:
    - timing:
      - ON for at most 1s
      - OFF for at most 1s
      - ON for at most 1s
      - OFF for at least 0.2s
      then:
        - logger.log: "Double Clicked"
        - homeassistant.event:
            event: esphome.babybuddy_panel_sleepstop
            data:
              title: dbl_click
    - timing:
      - ON for at most 1s
      - OFF for at most 1s
      - ON for at most 1s
      - OFF for at most 1s
      - ON for at most 1s
      - OFF for at least 0.2s
      then:
        - logger.log: "Triple Clicked"
        - homeassistant.event:
            event: esphome.babybuddy_panel_sleepstop
            data:
              title: triple_click
    - timing:
      - ON for 1s to 2s
      - OFF for at least 0.5s
      then:
        - logger.log: "Single Long Clicked"
        - homeassistant.event:
            event: esphome.babybuddy_panel_sleepstop
            data:
              title: long_click
    - timing:
      - ON for at least 2.2s
      then:
        - logger.log: "Click and Hold"
        - homeassistant.event:
            event: esphome.babybuddy_panel_sleepstop
            data:
              title: hold
    - timing:
      - ON for at most 1s
      - OFF for at least 0.5s
      then:
        - logger.log: "Single Short Clicked"
        - homeassistant.event:
            event: esphome.babybuddy_panel_sleepstop
            data:
              message: single_click
  #tummytimestart
  - platform: gpio
    pin:
      number: GPIO25
      mode:
        input: true
        pulldown: true #was pulldown
    id: tummytimestart
    on_multi_click:
    - timing:
      - ON for at most 1s
      - OFF for at most 1s
      - ON for at most 1s
      - OFF for at least 0.2s
      then:
        - logger.log: "Double Clicked"
        - homeassistant.event:
            event: esphome.babybuddy_panel_tummytimestart
            data:
              title: dbl_click
    - timing:
      - ON for at most 1s
      - OFF for at most 1s
      - ON for at most 1s
      - OFF for at most 1s
      - ON for at most 1s
      - OFF for at least 0.2s
      then:
        - logger.log: "Triple Clicked"
        - homeassistant.event:
            event: esphome.babybuddy_panel_tummytimestart
            data:
              title: triple_click
    - timing:
      - ON for 1s to 2s
      - OFF for at least 0.5s
      then:
        - logger.log: "Single Long Clicked"
        - homeassistant.event:
            event: esphome.babybuddy_panel_tummytimestart
            data:
              title: long_click
    - timing:
      - ON for at least 2.2s
      then:
        - logger.log: "Click and Hold"
        - homeassistant.event:
            event: esphome.babybuddy_panel_tummytimestart
            data:
              title: hold
    - timing:
      - ON for at most 1s
      - OFF for at least 0.5s
      then:
        - logger.log: "Single Short Clicked"
        - homeassistant.event:
            event: esphome.babybuddy_panel_tummytimestart
            data:
              title: single_click
  #tummytimestop
  - platform: gpio
    pin:
      number: GPIO32
      mode:
        input: true
        pulldown: true #was pulldown
    id: tummytimestop
    on_multi_click:
    - timing:
      - ON for at most 1s
      - OFF for at most 1s
      - ON for at most 1s
      - OFF for at least 0.2s
      then:
        - logger.log: "Double Clicked"
        - homeassistant.event:
            event: esphome.babybuddy_panel_tummytimestop
            data:
              title: dbl_click
    - timing:
      - ON for at most 1s
      - OFF for at most 1s
      - ON for at most 1s
      - OFF for at most 1s
      - ON for at most 1s
      - OFF for at least 0.2s
      then:
        - logger.log: "Triple Clicked"
        - homeassistant.event:
            event: esphome.babybuddy_panel_tummytimestop
            data:
              title: triple_click
    - timing:
      - ON for 1s to 2s
      - OFF for at least 0.5s
      then:
        - logger.log: "Single Long Clicked"
        - homeassistant.event:
            event: esphome.babybuddy_panel_tummytimestop
            data:
              title: long_click
    - timing:
      - ON for at least 2.2s
      then:
        - logger.log: "Click and Hold"
        - homeassistant.event:
            event: esphome.babybuddy_panel_tummytimestop
            data:
              title: hold
    - timing:
      - ON for at most 1s
      - OFF for at least 0.5s
      then:
        - logger.log: "Single Short Clicked"
        - homeassistant.event:
            event: esphome.babybuddy_panel_tummytimestop
            data:
              title: single_click
  #feedingstop
  - platform: gpio
    pin:
      number: GPIO14
      mode:
        input: true
        pulldown: true #was pulldown
    id: feedingstop
    on_multi_click:
    - timing:
      - ON for at most 1s
      - OFF for at most 1s
      - ON for at most 1s
      - OFF for at least 0.2s
      then:
        - logger.log: "Double Clicked"
        - homeassistant.event:
            event: esphome.babybuddy_panel_feedingstop
            data:
              title: dbl_click
    - timing:
      - ON for at most 1s
      - OFF for at most 1s
      - ON for at most 1s
      - OFF for at most 1s
      - ON for at most 1s
      - OFF for at least 0.2s
      then:
        - logger.log: "Triple Clicked"
        - homeassistant.event:
            event: esphome.babybuddy_panel_feedingstop
            data:
              title: triple_click
    - timing:
      - ON for 1s to 2s
      - OFF for at least 0.5s
      then:
        - logger.log: "Single Long Clicked"
        - homeassistant.event:
            event: esphome.babybuddy_panel_feedingstop
            data:
              title: long_click
    - timing:
      - ON for at least 2.2s
      then:
        - logger.log: "Click and Hold"
        - homeassistant.event:
            event: esphome.babybuddy_panel_feedingstop
            data:
              title: hold
    - timing:
      - ON for at most 1s
      - OFF for at least 0.5s
      then:
        - logger.log: "Single Short Clicked"
        - homeassistant.event:
            event: esphome.babybuddy_panel_feedingstop
            data:
              title: single_click
    #sleepstart
  - platform: gpio
    pin:
      number: GPIO26
      mode:
        input: true
        pulldown: true #was pulldown
    id: sleepstart
    on_multi_click:
    - timing:
      - ON for at most 1s
      - OFF for at most 1s
      - ON for at most 1s
      - OFF for at least 0.2s
      then:
        - logger.log: "Double Clicked"
        - homeassistant.event:
            event: esphome.babybuddy_panel_sleepstart
            data:
              title: dbl_click
    - timing:
      - ON for at most 1s
      - OFF for at most 1s
      - ON for at most 1s
      - OFF for at most 1s
      - ON for at most 1s
      - OFF for at least 0.2s
      then:
        - logger.log: "Triple Clicked"
        - homeassistant.event:
            event: esphome.babybuddy_panel_sleepstart
            data:
              title: triple_click
    - timing:
      - ON for 1s to 2s
      - OFF for at least 0.5s
      then:
        - logger.log: "Single Long Clicked"
        - homeassistant.event:
            event: esphome.babybuddy_panel_sleepstart
            data:
              title: long_click
    - timing:
      - ON for at least 2.2s
      then:
        - logger.log: "Click and Hold"
        - homeassistant.event:
            event: esphome.babybuddy_panel_sleepstart
            data:
              title: hold
    - timing:
      - ON for at most 1s
      - OFF for at least 0.5s
      then:
        - logger.log: "Single Short Clicked"
        - homeassistant.event:
            event: esphome.babybuddy_panel_sleepstart
            data:
              title: single_click
    #diaperwet
  - platform: gpio
    pin:
      number: GPIO12
      mode:
        input: true
        pulldown: true
    id: diaperwet
    on_multi_click:
    - timing:
      - ON for at most 1s
      - OFF for at most 1s
      - ON for at most 1s
      - OFF for at least 0.2s
      then:
        - logger.log: "Double Clicked"
        - homeassistant.event:
            event: esphome.babybuddy_panel_diaperwet
            data:
              title: dbl_click
    - timing:
      - ON for at most 1s
      - OFF for at most 1s
      - ON for at most 1s
      - OFF for at most 1s
      - ON for at most 1s
      - OFF for at least 0.2s
      then:
        - logger.log: "Triple Clicked"
        - homeassistant.event:
            event: esphome.babybuddy_panel_diaperwet
            data:
              title: triple_click
    - timing:
      - ON for 1s to 2s
      - OFF for at least 0.5s
      then:
        - logger.log: "Single Long Clicked"
        - homeassistant.event:
            event: esphome.babybuddy_panel_diaperwet
            data:
              title: long_click
    - timing:
      - ON for at least 2.2s
      then:
        - logger.log: "Click and Hold"
        - homeassistant.event:
            event: esphome.babybuddy_panel_diaperwet
            data:
              title: hold
    - timing:
      - ON for at most 1s
      - OFF for at least 0.5s
      then:
        - logger.log: "Single Short Clicked"
        - homeassistant.event:
            event: esphome.babybuddy_panel_diaperwet
            data:
              title: single_click
    #diapersolid
  - platform: gpio
    pin:
      number: GPIO13
      mode:
        input: true
        pulldown: true #was pulldown
    id: diapersolid
    on_multi_click:
    - timing:
      - ON for at most 1s
      - OFF for at most 1s
      - ON for at most 1s
      - OFF for at least 0.2s
      then:
        - logger.log: "Double Clicked"
        - homeassistant.event:
            event: esphome.babybuddy_panel_diapersolid
            data:
              title: dbl_click
    - timing:
      - ON for at most 1s
      - OFF for at most 1s
      - ON for at most 1s
      - OFF for at most 1s
      - ON for at most 1s
      - OFF for at least 0.2s
      then:
        - logger.log: "Triple Clicked"
        - homeassistant.event:
            event: esphome.babybuddy_panel_diapersolid
            data:
              title: triple_click
    - timing:
      - ON for 1s to 2s
      - OFF for at least 0.5s
      then:
        - logger.log: "Single Long Clicked"
        - homeassistant.event:
            event: esphome.babybuddy_panel_diapersolid
            data:
              title: long_click
    - timing:
      - ON for at least 2.2s
      then:
        - logger.log: "Click and Hold"
        - homeassistant.event:
            event: esphome.babybuddy_panel_diapersolid
            data:
              title: hold
    - timing:
      - ON for at most 1s
      - OFF for at least 0.5s
      then:
        - logger.log: "Single Short Clicked"
        - homeassistant.event:
            event: esphome.babybuddy_panel_diapersolid
            data:
              title: single_click
    #feedingstart
  - platform: gpio
    pin:
      number: GPIO27
      mode:
        input: true
        pulldown: true
    id: feedingstart
    on_multi_click:
    - timing:
      - ON for at most 1s
      - OFF for at most 1s
      - ON for at most 1s
      - OFF for at least 0.2s
      then:
        - logger.log: "Double Clicked"
        - homeassistant.event:
            event: esphome.babybuddy_panel_feedingstart
            data:
              title: dbl_click
    - timing:
      - ON for at most 1s
      - OFF for at most 1s
      - ON for at most 1s
      - OFF for at most 1s
      - ON for at most 1s
      - OFF for at least 0.2s
      then:
        - logger.log: "Triple Clicked"
        - homeassistant.event:
            event: esphome.babybuddy_panel_feedingstart
            data:
              title: triple_click
    - timing:
      - ON for 1s to 2s
      - OFF for at least 0.5s
      then:
        - logger.log: "Single Long Clicked"
        - homeassistant.event:
            event: esphome.babybuddy_panel_feedingstart
            data:
              title: long_click
    - timing:
      - ON for at least 2.2s
      then:
        - logger.log: "Click and Hold"
        - homeassistant.event:
            event: esphome.babybuddy_panel_feedingstart
            data:
              title: hold
    - timing:
      - ON for at most 1s
      - OFF for at least 0.5s
      then:
        - logger.log: "Single Short Clicked"
        - homeassistant.event:
            event: esphome.babybuddy_panel_feedingstart
            data:
              title: single_click
            